[phases.setup]
aptPkgs = ["hugo"]
nixPkgs = ["nodejs_22"]

[variables]
HUGO_ENABLEGITINFO = 'false'

[phases.install] 
cmds = [
  'npm install -g pnpm@latest && pnpm install'  # ← Same shell session!
]

[phases.build]
cmds = [
  'npx pnpm run build'  # ← npx finds globally installed pnpm
]

[[nixpacks.included_files]]
paths = ["/public"]