[phases.setup]
aptPkgs = ["hugo"]
nixPkgs = ["nodejs_22"]
cmds = ["npm install -g pnpm@latest"]

[environment]
HUGO_VERSION = "0.148.2"

[variables]
HUGO_ENABLEGITINFO = 'false'

[phases.install]
cmds = [
  'pnpm install'
]

[phases.build]
cmds = [
  'pnpm run build'
]

[[nixpacks.included_files]]
paths = ["/public"]