[phases.setup]
nixPkgs = [
  'nodejs_22',
  'hugo'
]

[variables]
HUGO_ENABLEGITINFO = 'false'

[phases.install]
cmds = [
  'npm install -g pnpm@latest',
  'pnpm install'
]

[phases.build]
cmds = [
  'pnpm run build'
]
