[phases.setup]
aptPkgs = ["hugo"]
nixPkgs = ["nodejs_22"]

[environment]
HUGO_VERSION = "0.148.2"

[variables]  
HUGO_ENABLEGITINFO = 'false'

[phases.build]
cmds = [
  'npm install',
  'npm run build'
]

[[nixpacks.included_files]]
paths = ["/public"]