[phases.setup]
aptPkgs = ["hugo"]
nixPkgs = ["nodejs_22"]

[environment]
HUGO_VERSION = "0.148.2"

[variables]
HUGO_ENABLEGITINFO = 'false'

[phases.install]
cmds = [
  'cd tailbliss && npm install'
]

[phases.build]
cmds = [
  'cd tailbliss && npm run build'
]

[[nixpacks.included_files]]
paths = ["/tailbliss/public"]